apiVersion: v1
kind: Pod
metadata:
  name: vault
  namespace: lab1
  labels:
    app: vault
spec:
  containers:
    - name: vault
      image: vault:1.13.3
      ports:
        - name: http
          containerPort: 8200
          protocol: TCP
      resources:
        limits:
          cpu: 200m
          memory: 200Mi
