apiVersion: crd.projectcalico.org/v1
kind: IPPool
metadata:
  name: lomo-ippool
spec:
  cidr: 10.200.0.0/24
  ipipMode: Always
  natOutgoing: true
  nodeSelector: zone == "lomo"
---
apiVersion: crd.projectcalico.org/v1
kind: IPPool
metadata:
  name: kronva-ippool
spec:
  cidr: 10.200.1.0/24
  ipipMode: Always
  natOutgoing: true
  nodeSelector: zone == "kronva"
